version: 1
formatters:
  brief:
    format: '%(levelname)s - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
loggers:
  sdm.core:
    level: INFO
    handlers: [console]
  sdm.main:
    level: INFO
    handlers: [console]
  sdm.utils.FileMerger.filesmerger.HierarchicalMerger:
    level: WARN
    handlers: [console]
  sdm.utils.FileMerger.filesmerge.core:
    level: WARN
    handlers: [console]
  sdm.utils.corpus_utils:
    level: WARN
    handlers: [console]
  sdm.utils.Pipeline:
    level: DEBUG
    handlers: [console]

